version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: tiJ8AHiV6IkCcXVW6/4ZchNUMY77TqPd+Ebvzg6MnI/F4vjEcph76ykrtvr0zZ5R

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install

build_script:
  - yarn run dist:win

test: off
